'use babel'

class Language {
  constructor(name, code) {
    this.name = name
    this.code = code
  }
  static getFromName(name) {
    for (const lang of Language.list) {
      if (lang.name === name) {
        return lang
      }
    }
    return null
  }
  static getFromCode(code) {
    for (const lang of Language.list) {
      if (lang.code === code) {
        return lang
      }
    }
    return null
  }
}

// Language list from [this site](https://github.com/wooorm/franc/blob/master/Supported-Languages.md)
Language.list = [
  new Language("Mandarin Chinese", "cmn"),
  new Language("Spanish", "spa"),
  new Language("English", "eng"),
  new Language("Russian", "rus"),
  new Language("Standard Arabic", "arb"),
  new Language("Bengali", "ben"),
  new Language("Hindi", "hin"),
  new Language("Portuguese", "por"),
  new Language("Indonesian", "ind"),
  new Language("Japanese", "jpn"),
  new Language("French", "fra"),
  new Language("German", "deu"),
  new Language("Javanese", "jav"),
  new Language("Korean", "kor"),
  new Language("Telugu", "tel"),
  new Language("Vietnamese", "vie"),
  new Language("Marathi", "mar"),
  new Language("Italian", "ita"),
  new Language("Tamil", "tam"),
  new Language("Turkish", "tur"),
  new Language("Urdu", "urd"),
  new Language("Gujarati", "guj"),
  new Language("Polish", "pol"),
  new Language("Ukrainian", "ukr"),
  new Language("Maithili", "mai"),
  new Language("Malayalam", "mal"),
  new Language("Kannada", "kan"),
  new Language("Burmese", "mya"),
  new Language("Oriya (macrolanguage)", "ori"),
  new Language("Borana-Arsi-Guji Oromo", "gax"),
  new Language("Swahili (individual language)", "swh"),
  new Language("Sundanese", "sun"),
  new Language("Romanian", "ron"),
  new Language("Panjabi", "pan"),
  new Language("Bhojpuri", "bho"),
  new Language("Amharic", "amh"),
  new Language("Pulaar", "fuc"),
  new Language("Hausa", "hau"),
  new Language("Bosnian", "bos"),
  new Language("Croatian", "hrv"),
  new Language("Dutch", "nld"),
  new Language("Serbian", "srp"),
  new Language("Thai", "tha"),
  new Language("Central Kurdish", "ckb"),
  new Language("Yoruba", "yor"),
  new Language("Northern Uzbek", "uzn"),
  new Language("Igbo", "ibo"),
  new Language("Nepali (macrolanguage)", "nep"),
  new Language("Cebuano", "ceb"),
  new Language("Seraiki", "skr"),
  new Language("Tagalog", "tgl"),
  new Language("Hungarian", "hun"),
  new Language("North Azerbaijani", "azj"),
  new Language("Sinhala", "sin"),
  new Language("Modern Greek (1453-)", "ell"),
  new Language("Czech", "ces"),
  new Language("Magahi", "mag"),
  new Language("Belarusian", "bel"),
  new Language("Plateau Malagasy", "plt"),
  new Language("Madurese", "mad"),
  new Language("Nyanja", "nya"),
  new Language("Chimborazo Highland Quichua", "qug"),
  new Language("Kinyarwanda", "kin"),
  new Language("Zulu", "zul"),
  new Language("Bulgarian", "bul"),
  new Language("Swedish", "swe"),
  new Language("Lingala", "lin"),
  new Language("Somali", "som"),
  new Language("Southern Qiandong Miao", "hms"),
  new Language("Iloko", "ilo"),
  new Language("Kazakh", "kaz"),
  new Language("Uighur", "uig"),
  new Language("Haitian", "hat"),
  new Language("Central Khmer", "khm"),
  new Language("Akan", "aka"),
  new Language("Hiligaynon", "hil"),
  new Language("Iranian Persian", "pes"),
  new Language("Shona", "sna"),
  new Language("Tatar", "tat"),
  new Language("Xhosa", "xho"),
  new Language("Armenian", "hye"),
  new Language("Minangkabau", "min"),
  new Language("Afrikaans", "afr"),
  new Language("Luba-Lulua", "lua"),
  new Language("Santali", "sat"),
  new Language("Tibetan", "bod"),
  new Language("Tigrinya", "tir"),
  new Language("Finnish", "fin"),
  new Language("Rundi", "run"),
  new Language("Slovak", "slk"),
  new Language("Turkmen", "tuk"),
  new Language("Danish", "dan"),
  new Language("Tosk Albanian", "als"),
  new Language("Norwegian Bokmål", "nob"),
  new Language("Sukuma", "suk"),
  new Language("Sango", "sag"),
  new Language("Norwegian Nynorsk", "nno"),
  new Language("Hebrew", "heb"),
  new Language("Mossi", "mos"),
  new Language("Tajik", "tgk"),
  new Language("Catalan", "cat"),
  new Language("Southern Sotho", "sot"),
  new Language("Georgian", "kat"),
  new Language("Central Bikol", "bcl"),
  new Language("Galician", "glg"),
  new Language("Lithuanian", "lit"),
  new Language("Lao", "lao"),
  new Language("Umbundu", "umb"),
  new Language("Tswana", "tsn"),
  new Language("Pedi", "nso"),
  new Language("Balinese", "ban"),
  new Language("Buginese", "bug"),
  new Language("Central Kanuri", "knc"),
  new Language("Ibibio", "ibb"),
  new Language("Ganda", "lug"),
  new Language("Achinese", "ace"),
  new Language("Bambara", "bam"),
  new Language("Kimbundu", "kmb"),
  new Language("Lunda", "lun"),
  new Language("Central Atlas Tamazight", "tzm"),
  new Language("Waray (Philippines)", "war"),
  new Language("Eastern Yiddish", "ydd"),
  new Language("Wolof", "wol"),
  new Language("Kirghiz", "kir"),
  new Language("Low German", "nds"),
  new Language("Macedonian", "mkd"),
  new Language("Makhuwa", "vmw"),
  new Language("Ewe", "ewe"),
  new Language("Halh Mongolian", "khk"),
  new Language("Slovenian", "slv"),
  new Language("Central Aymara", "ayr"),
  new Language("Bemba (Zambia)", "bem"),
  new Language("Eastern Maninkakan", "emk"),
  new Language("Baoulé", "bci"),
  new Language("Esperanto", "epo"),
  new Language("Pampanga", "pam"),
  new Language("Tiv", "tiv"),
  new Language("Tok Pisin", "tpi"),
  new Language("Swati", "ssw"),
  new Language("Nyankole", "nyn"),
  new Language("Sichuan Yi", "iii"),
  new Language("Yao", "yao"),
  new Language("Latvian", "lav"),
  new Language("Cusco Quechua", "quz"),
  new Language("Vlax Romani", "rmy"),
  new Language("Logudorese Sardinian", "src"),
  new Language("Scots", "sco"),
  new Language("Tsonga", "tso"),
  new Language("Mende (Sierra Leone)", "men"),
  new Language("Fon", "fon"),
  new Language("Central Nahuatl", "nhn"),
  new Language("Northeastern Dinka", "dip"),
  new Language("Makonde", "kde"),
  new Language("Siona", "snn"),
  new Language("Kabiyè", "kbp"),
  new Language("Timne", "tem"),
  new Language("Tonga (Zambia)", "toi"),
  new Language("Estonian", "est"),
  new Language("Soninke", "snk"),
  new Language("Chokwe", "cjk"),
  new Language("Adangme", "ada"),
  new Language("Assyrian Neo-Aramaic", "aii"),
  new Language("Bini", "bin"),
  new Language("Ga", "gaa"),
  new Language("Koongo", "kng"),
  new Language("Ndonga", "ndo"),
  new Language("Ayacucho Quechua", "quy"),
  new Language("Balkan Romani", "rmn")
]
export default Language
